#!/bin/bash
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=30
#SBATCH --time=24:00:00
#SBATCH --output=slurm-out/%x.o%j
#SBATCH --error=slurm-out/%x.e%j

# USAGE: export ASSM='Elysia-flye-racon1-medaka-nextpolish'; export LINEAGE='mollusca_odb10'; sbatch --mail-user=$EMAIL -J "${ASSM}-${LINEAGE}-busco" scripts/run_busco_protein.sub 

module load busco

CWD=$PWD
PROTEOME="$CWD/${ASSM}-proteins.fa"
OUTDIR="$CWD/${ASSM}-${LINEAGE}"

mkdir -p $OUTDIR
cd $OUTDIR

echo busco -i $PROTEOME --cpu 30 --out ${ASSM}-${LINEAGE} -m protein --lineage_dataset $LINEAGE --force
busco -i $PROTEOME --cpu 30 --out ${ASSM}-${LINEAGE} -m protein --lineage_dataset $LINEAGE --force