#!/bin/bash
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --cpus-per-task=48
#SBATCH --time=24:00:00     
#SBATCH --output=slurm-out/%x.o%j
#SBATCH --error=slurm-out/%x.e%j

# usage: export ASSM='assembly version'; sbatch --mail-user=$EMAIL -J "star-${ASSM}" scripts/3_run_star_alignment.sub

module load star 

#User defined parameters
OUTDIR="3_Alignment/${ASSM}"
mkdir -p $OUTDIR

cd $OUTDIR
ASSMFILE="../../genomes/${ASSM}.fa.masked.cleanheaders"
READFILE='../read_manifest.tsv'
THREADS=40

echo STAR --runThreadN $THREADS --runMode genomeGenerate --genomeSAindexNbases 13 --genomeFastaFiles $ASSMFILE 
STAR --runThreadN $THREADS --runMode genomeGenerate --genomeSAindexNbases 13 --genomeFastaFiles $ASSMFILE 

echo STAR --runThreadN $THREADS --runMode alignReads --readFilesManifest $READFILE --readFilesCommand gunzip -c --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 16237284432 --outBAMsortingThreadN 1
STAR --runThreadN $THREADS --runMode alignReads --readFilesManifest $READFILE --readFilesCommand gunzip -c --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 16237284432 --outBAMsortingThreadN 1

