#!/bin/bash
#SBATCH --job-name=Bp_trinity
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=128
#SBATCH --time=2-00:00:00     
#SBATCH --output=slurm-out/%x.o%j
#SBATCH --error=slurm-out/%x.e%j

# usage: sbatch --mail-user=$EMAIL scripts/4_run_trinity.sub

module load trinity    

cd 4_Trinity

Trinity --seqType fq --samples_file read_manifest.tsv  --max_memory 120G --CPU 120

