#!/bin/bash
#SBATCH --job-name=kallistoindex
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=120G
#SBATCH --time=24:00:00     
#SBATCH --output=slurm-out/%x.o%j
#SBATCH --error=slurm-out/%x.e%j

# USAGE: export TRANSCRIPTOMEFILEPATH='3_IndexGenome/transcriptome.fa'; sbatch --mail-user=$EMAIL -J index-${TRANSCRIPTOMEFILE} scripts/3_run_kallisto_index.sub
### TRANSCRIPTOMEFILEPATH should be the absolute or relative path to the full predicted transcriptome 
###(all full lenth mRNA including alternative spice variants)

module load conda-env/kallisto-py3.8.3      

#User defined parameters
INDEX="${TRANSCRIPTOMEFILEPATH}.kallisto.index"

echo kallisto index -i $INDEX $TRANSCRIPTOMEFILEPATH
kallisto index -i $INDEX $TRANSCRIPTOMEFILEPATH

