#!/bin/bash
#SBATCH --job-name=multiqc
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=24:00:00     
#SBATCH --output=slurm-out/%x.o%j
#SBATCH --error=slurm-out/%x.e%j

# usage: export DIR='sample directory'; sbatch --mail-user=$EMAIL scripts/run_multiqc.sub

module load conda-env/read_preprocessing-py3.8.3  

multiqc $DIR --outdir $DIR

